title: <p align="center"> Monika Clementraj </p>
logo: /assets/img/logo.png
description:
<p align="center">
<a href="https://github.com/Monikaraj1999">Github</a>

<br>
I'm currently doing MS in Machine Learning and Artificial Intelligence and also handling Projects on that.
Working with Infosys for 2 years.
</br>
</p>

theme: jekyll-theme-minimal
